### ISSUE TITLE
Testimine

### ISSUE THREAD

**Issue by Anne-dot** [JakobVapper/e-commerce-product-inventory-system#2]
Manuaalne testimine ja tagasiside andmine. AI abil testimise katsetamine

**Comment by Ottonuum** [comment]
1. Segane front disaini puudmise pärast.
2. Mõned errorid puuduvad editimisel.

**Comment by Anne-dot** [comment]
![image](https://github.com/user-attachments/assets/38bbf937-a813-4a7f-bcb0-ba80bc3ef342)

**Comment by Anne-dot** [comment]
Korras
