### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by Anne-dot** [JakobVapper/e-commerce-product-inventory-system#5]
Disaini meeskonnale. Leida abistav töövahend, teha valmis ja anda arendusmeeskonnale kasutamiseks

**Comment by MrBruhButBetter** [comment]
link rel="icon" type="image/x-icon" href="/FOLDER-PATH/IMAGE-NAME"

![image_2024-10-04_122224616](https://github.com/user-attachments/assets/3e16048c-ac1f-4c9b-86cd-019dc2359faf)

**Comment by MrBruhButBetter** [comment]
<link rel="icon" type="image/x-icon" href="/FOLDER-PATH/IMAGE-NAME">
